server:
    port: 8086
spring:
    application:
         name: make-reservation-service
    data:
     mongodb:
      host: localhost
      port: 27017
      database: reservationdb
    main:
      allow-circular-references: true
    mail:
      host: smtp.gmail.com
      port: 587
      username: guptavishu0508@gmail.com
      password: pvhnmftptrjtvnxb
      properties:
        mail:
          smtp:
            auth: true
            starttls:
                enable: true