server:
      port: 8084
spring:
     application:
            name: retrieve-report-service
     banner:
        location: banner.txt
     data:
             mongodb:
                    host: localhost
                    port: 27017
                    database: reportdb
     main:
              allow-circular-references: true
logging:
  level:
    com:
      capgemini:
       retrievereportservice: INFO       