spring:
    application:
            name: manage-inventory-service
    banner:
      location: banner.txt
    datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/inventoryDB
     username: root
     password: 12345678
    jpa:
     hibernate.ddl-auto: update
     generate-ddl: true
     show-sql: true
server:
    port: 8082
logging:
  level:
    com:
      capgemini:
        manageinventoryservice: INFO    